# Generated by Django 5.2.5 on 2025-08-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0004_alter_lesson_options_alter_mark_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
