# Generated by Django 5.2 on 2025-08-30 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0005_lesson_end_time_lesson_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='answer',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
