# Generated by Django 5.2 on 2025-08-30 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0006_alter_mark_answer_alter_mark_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='edu.lesson'),
        ),
    ]
